project_id = "ykqjffokjdpnqeiovmnp"

[functions.export-resume]
verify_jwt = false

[functions.enhance-text]
verify_jwt = false

[functions.ats-check]
verify_jwt = false

[functions.job-match]
verify_jwt = false
